# Generated by Django 2.2.14 on 2021-01-25 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='bike_type',
            field=models.CharField(choices=[('R15', 'R15'), ('Hero', 'Hero'), ('yamma', 'yamma')], max_length=250),
        ),
        migrations.AlterField(
            model_name='service',
            name='type',
            field=models.CharField(choices=[('engin', 'engin'), ('wash', 'wash'), ('glass', 'glass'), ('breakplate', 'breakplate')], max_length=200),
        ),
    ]
