# Generated by Django 2.2.14 on 2021-01-28 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_buy_parts'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy_parts',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
